mini_tweets/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include


urlpatterns += [
    path('home/', include('tweets.urls')),
]

# Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/home/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tweets/urls.py
from django.urls import include, path

from . import views


urlpatterns = [
    path('', views.PostListView.as_view(), name="homefeeds"),
    path('post/<int:pk>', views.PostDetailView.as_view(), name="post-detail"),
    path('account/<int:pk>', views.UserAccountPostListView.as_view(), name="post-list-by-user"),

    path('post/create/', views.PostTweetCreate.as_view(), name='post-create'),
    path('comment/<int:pk>/create/', views.PostCommentCreate.as_view(), name='comment-create'),
]

tweets/models.py
from django.db import models

# Create your models here.
from datetime import date
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User #Blog author or commenter

class UserAccount(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")
    
    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular account user.
        """
        return reverse('account', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username

class Post(models.Model):
    """
    Model representing a post tweets.
    """
    useraccount = models.ForeignKey(UserAccount, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because Post can only have one User Account, but User Accounts can have multiple posts tweets.
    caption = models.TextField(max_length=2000, help_text="Enter you tweets text here.")
    post_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["-post_date"]
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular post tweets instance.
        """
        return reverse('post-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.caption

class PostComment(models.Model):
    """
    Model representing a comment against a post tweets.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about post here.")
    useraccount = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because PostComment can only have one UserAccount, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    post= models.ForeignKey(Post, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=130
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

tweets/views.py
from django.shortcuts import render

from .models import Post, PostComment, UserAccount

from django.views import generic

from django.contrib.auth.models import User

class PostListView(generic.ListView):
    model = Post
    template_name = "tweets/index.html"

class PostDetailView(generic.DetailView):
    model = Post

from django.shortcuts import get_object_or_404
class UserAccountPostListView(generic.ListView):
    model = Post
    template_name = "tweets/useraccount_post_list_view.html"

    def get_queryset(self):

        """
        Return list of Post objects created by UserAccout (useraccount id specified in URL)
        """
        id = self.kwargs['pk']
        target_useraccount = get_object_or_404(UserAccount, pk=id)
        return Post.objects.filter(useraccount=target_useraccount)
    
    def get_context_data(self, **kwargs):
        """
        Add UserAccount to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(UserAccountPostListView, self).get_context_data(**kwargs)
        # Get the useraccount object from the "pk" URL parameter and add it to the context
        context['useraccount'] = get_object_or_404(UserAccount, pk= self.kwargs['pk'])
        return context

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse

class PostCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
    model = PostComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(PostCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['post'] = get_object_or_404(Post, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.useraccount = self.request.user
        #Associate comment with blog based on passed id
        form.instance.post = get_object_or_404(Post, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(PostCommentCreate, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('post-detail', kwargs={'pk': self.kwargs['pk'],})

    
class PostTweetCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a Post Create. Requires login. 
    """
    model = Post
    fields = ['caption',]


    def form_valid(self, form):
        """
        Add author and associated post to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of poster
        form.instance.useraccount = get_object_or_404(UserAccount, user= self.request.user)

        return super(PostTweetCreate, self).form_valid(form)
    

tweets/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Tweets</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <header>
      <nav class="navbar fixed-top navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'homefeeds' %}">
            <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/Tweets.png?alt=media&token=204a5c8e-f25a-4873-b88d-e21a26a30294" alt="" width="150" height="auto">
          </a>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-sm-2 sidebar-nav">
          {% block sidebar %}
          <div class="">
            <ul>
                <li><a href="{% url 'homefeeds' %}"><i class="fa-solid fa-house-user"></i>Home</a></li>
                <li><a href="#"><i class="fa-solid fa-circle-user"></i>Profile</a></li>
            </ul>
            {% if user.is_authenticated %}
            <div class="d-grid gap-2">
              <button class="btn btn-primary" type="button"> <a href="{% url 'post-create' %}"><i class="fa-solid fa-add"></i>Tweet</a> </button>
            </div>
            {% endif %}

          </div>
          <ul>

            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-link">Logout</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
          {% endif %}
          {% endblock %}
        </ul>

        </div>
        <div class="col-sm-7 main">{% block content %}{% endblock %}</div>
      </div>
    </div>
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/5b19ade4fd.js" crossorigin="anonymous"></script>
  </body>
</html>

tweets/templates/home.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>NewsFeeds</h1>

  <div class="container newsfeed">
    <div class="useraccount">
      <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/circle-user-regular-light.svg?alt=media&token=0e2e0b6f-6332-4871-ada9-5fe1848bf83c" alt="">
      <strong>Fabrizio Romano</strong>
      <label>@fabrizioromano</label>
      <span>·</span>
      <label>10h</label>
    </div>
    <div class="caption">
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quae harum voluptate cumque obcaecati consectetur dolores in fugiat fuga quo excepturi nostrum omnis, neque sapiente fugit placeat dolor laudantium incidunt tenetur.</p>
    </div>
    <div class="d-grid gap-2">
      <button class="btn btn-outline-light" type="button"> More Details <i class="fa-solid fa-chevron-down"></i></button>
    </div>
  </div>
{% endblock %}

tweets/templates/tweets/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>NewsFeeds</h1>

  {% if post_list %}

    {% for post in post_list %}
    <div class="container newsfeed">
      <div class="useraccount">
        <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/circle-user-regular-light.svg?alt=media&token=0e2e0b6f-6332-4871-ada9-5fe1848bf83c" alt="">
        <strong><a href="{% url 'post-list-by-user' post.useraccount.pk %}"> {{ post.useraccount }} </a></strong>
        <span>·</span>
        <label>{{ post.post_date }}</label>
      </div>
      <div class="caption">
        <p>{{ post.caption }}</p>
      </div>
      <div class="d-grid gap-2">
        <button class="btn btn-dark" type="button"> <a href="{{ post.get_absolute_url }}">More Details <i class="fa-solid fa-chevron-down"></i></a> </button>
      </div>
    </div>
    {% endfor %}

  {% else %}
  <p>There is no any post.</p>
  {% endif %}
{% endblock %}

tweets/templates/tweets/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h3 class="post-detail-nav"> <a href="{% url 'homefeeds' %}"><i class="fa-solid fa-arrow-left"></i></a> Post</h3>
 
  <div class="container post-detail">
      <div class="useraccount">
        <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/circle-user-regular-light.svg?alt=media&token=0e2e0b6f-6332-4871-ada9-5fe1848bf83c" alt="">
        <div>
          <strong>{{ post.useraccount }}</strong>
          <p class="user-handle">@{{ post.useraccount }}</p>
        </div>
      </div>
      <div class="caption">
        <p>{{ post.caption }}</p>
      </div>
      <div class="datetime">
        <p> {{ post.post_date }} </p>
        <div>·</div>
        <p>8:00 AM</p>
      </div>
    </div>

    <div class="comment-section">
      <h4>Comments</h4>
    
      

      {% for comment in post.postcomment_set.all %}

      <div class="comment-feeds">
        <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/circle-user-regular-light.svg?alt=media&token=0e2e0b6f-6332-4871-ada9-5fe1848bf83c" alt="">
        <div>
          <strong>{{ comment.useraccount }}</strong>
          <span>·</span>
          <label>{{ comment.post_date }}</label>
        </div>
      </div>
      <div class="caption">
        <p>{{ comment.description }}</p>
      </div>
      {% empty %}
      <p class="empty-comment-msg">The post has no comment.</p>
      {% endfor %}

      <hr>
      {% if user.is_authenticated %}
        <button class="btn btn-primary" type="button"> <a href="{% url 'comment-create' post.id %}"><i class="fa-solid fa-add"></i>Add a new comment</a> </button>
      {% else %}
        <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
      {% endif %} 
    </div>

{% endblock %}

tweets/templates/tweets/post_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

tweets/templates/tweets/postcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'post-detail' post.pk %}">{{ post.caption }}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

tweets/templates/tweets/useraccount_post_list_view.html
{% extends "base_generic.html" %}

{% block content %}
  <h3 class="post-detail-nav"> <a href="{% url 'homefeeds' %}"><i class="fa-solid fa-arrow-left"></i></a> {{ useraccount }}</h3>
 
    <div class="container account-profile">
      <div class="useraccount">
        <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/circle-user-regular-light.svg?alt=media&token=0e2e0b6f-6332-4871-ada9-5fe1848bf83c" alt="">
        <div>
          <strong>{{ useraccount }}</strong>
          <p class="user-handle">@{{ useraccount }}</p>
        </div>
      </div>
      <div class="user-bio">
        <p> {{ useraccount.bio }}</p>
      </div>
      <h5>Posts</h5>
    </div>

    {% if post_list %}
    {% for post in post_list %}
    <div class="container newsfeed">
      <div class="useraccount">
        <img src="https://firebasestorage.googleapis.com/v0/b/instagram-firebase-25884.appspot.com/o/circle-user-regular-light.svg?alt=media&token=0e2e0b6f-6332-4871-ada9-5fe1848bf83c" alt="">
        <strong>{{ post.useraccount }}</strong>
        <span>·</span>
        <label>{{ post.post_date }}</label>
      </div>
      <div class="caption">
        <p>{{ post.caption }}</p>
      </div>
      <div class="d-grid gap-2">
        <button class="btn btn-dark" type="button"> <a href="{{ post.get_absolute_url }}">More Details <i class="fa-solid fa-chevron-down"></i></a> </button>
      </div>
    </div>
    {% endfor %}

    {% else %}
    <p>There is no any post.</p>
    {% endif %}

{% endblock %}